# Generated by Django 6.0.1 on 2026-01-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('HTML', 'HTML'), ('JSON', 'JSON'), ('TEXT', 'TEXT')], default='HTML', max_length=4)),
                ('monitoring_frequency', models.IntegerField(choices=[('HOUR', 'Hourly'), ('DAY', 'Daily'), ('WEEK', 'Weekly'), ('MONT', 'Monthly')], default='DAY', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('is_snapshotting', models.BooleanField(default=False)),
            ],
        ),
    ]
