# Generated by Django 6.0.1 on 2026-01-14 10:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resource',
            name='monitoring_frequency',
            field=models.CharField(choices=[('HOUR', 'Hourly'), ('DAY', 'Daily'), ('WEEK', 'Weekly'), ('MONT', 'Monthly')], default='DAY', max_length=4),
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_hash', models.TextField()),
                ('status_code', models.IntegerField()),
                ('size', models.IntegerField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
            ],
        ),
    ]
