# Generated by Django 6.0.1 on 2026-01-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_registration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='last_snapshot',
            field=models.DateTimeField(null=True),
        ),
    ]
