# Generated by Django 6.0.1 on 2026-01-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_last_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='last_snapshot',
        ),
    ]
